hfhk:
  server:
    port: 10030
  auth:
    server: auth.hfhksoft.com
    client:
      id: hfhk_dhgxjsj
      secret: hfhk_dhgxjsj
  mongo:
    database: hfhk-cb
    authentication-database: hfhk
    host: 192.168.30.21
    port: 27017
    username: hfhk
    password: Hfhk.1320.
  redis:
    database: 11
    host: 192.168.30.21
    port: 6379
    password: Hfhk.1320.
  consul:
    host: 192.168.30.22
    port: 8500
    discovery:
      instance-zone: hfhk
      instance-group: hfhk


