version: '3.7'

networks:
  consul: { }

services:
  consul_m_1:
    image: consul:1.9.1
    command: agent -server -client=0.0.0.0 -bootstrap-expect=3 -node=m1 -datacenter=hfhk -ui
    networks:
      consul:
        aliases:
          - m1
    ports:
      - 8500:8500
    tty: true
    stdin_open: true
    restart: unless-stopped
  consul_n_1:
    image: consul:1.9.1
    hostname: n1
    command: agent -server -client=0.0.0.0 -retry-join=m1 -node=n1 -datacenter=hfhk
    networks:
      consul:
        aliases:
          - n1
    ports: [ ]
    tty: true
    stdin_open: true
    restart: unless-stopped
  consul_n_2:
    image: consul:1.9.1
    hostname: n2
    command: agent -server -client=0.0.0.0 -retry-join=m1 -node=n2 -datacenter=hfhk
    networks:
      consul:
        aliases:
          - n2
    ports: [ ]
    tty: true
    stdin_open: true
    restart: unless-stopped
  consul_n_3:
    image: consul:1.9.1
    hostname: n3
    command: agent -server -client=0.0.0.0 -retry-join=m1 -node=n3 -datacenter=hfhk
    networks:
      consul:
        aliases:
         - n3
    ports: [ ]
    tty: true
    stdin_open: true
    restart: unless-stopped
